# ==================
# LOG CONFIGURATION
# ==================

version: 1

disable_existing_loggers: false

incremental: false

root:
  level: DEBUG
  handlers: [ hSyslog ]

loggers:
  zzz:
    level: WARNING
    propagate: true

handlers:
  hSyslog:
    class: pysolbase.SysLogger.SysLogger
    level: DEBUG
    formatter: FDEFAULT
    address: "/dev/log"
    facility: 17

formatters:
  FDEFAULT:
    format: "%(asctime)s | %(levelname)s | %(module)s@%(funcName)s@%(lineno)d | %(message)s | %(kfilter)s | %(thread)d:%(threadName)s | %(process)d:%(processName)s"
    datefmt: ""
