# ==================
# LOG CONFIGURATION
# ==================

version: 1

disable_existing_loggers: false

root:
  level: DEBUG
  handlers: [ hSyslog ]
  propagate: false

loggers:
  zzz:
    level: WARNING
    handlers: [ hSyslog ]
    propagate: false

handlers:
  hSyslog:
    class: pysolbase.SysLogger.SysLogger
    level: DEBUG
    formatter: FDEFAULT

formatters:
  FDEFAULT:
    format: "%(asctime)s | %(levelname)s | %(module)s@%(funcName)s@%(lineno)d | %(message)s | %(kfilter)s | %(thread)d:%(threadName)s | %(process)d:%(processName)s"
    datefmt: ""
